//
// AccountForgotPasswordVerify.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AccountForgotPasswordVerify: Codable {

    /** ID of subaccount */
    public var subaccountId: Int
    /** Activation token */
    public var activationToken: String
    /** Password */
    public var password: String

    public init(subaccountId: Int, activationToken: String, password: String) {
        self.subaccountId = subaccountId
        self.activationToken = activationToken
        self.password = password
    }

    public enum CodingKeys: String, CodingKey { 
        case subaccountId = "subaccount_id"
        case activationToken = "activation_token"
        case password
    }


}

