//
// AccountVerify.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Verifies an account by token that should have been sent to the user&#39;s phone */

public struct AccountVerify: Codable {

    /** Country code */
    public var country: String
    /** User&#39;s phone number */
    public var userPhone: String
    /** Type of verification */
    public var type: String

    public init(country: String, userPhone: String, type: String) {
        self.country = country
        self.userPhone = userPhone
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case country
        case userPhone = "user_phone"
        case type
    }


}

