//
// FaxMessageCollection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Array of FaxMessage items */

public struct FaxMessageCollection: Codable {

    /** Array of FaxMessage items */
    public var messages: [FaxMessage]
    /** URL of file to send */
    public var fileUrl: String

    public init(messages: [FaxMessage], fileUrl: String) {
        self.messages = messages
        self.fileUrl = fileUrl
    }

    public enum CodingKeys: String, CodingKey { 
        case messages
        case fileUrl = "file_url"
    }


}

