//
// Fields.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains all details for the main contact. */

public struct Fields: Codable {

    public var fields: FieldsFields?

    public init(fields: FieldsFields?) {
        self.fields = fields
    }


}

