//
// ForgotPassword.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ForgotPassword: Codable {

    /** Username belonging to account. */
    public var username: String

    public init(username: String) {
        self.username = username
    }


}

