//
// MmsMessageCollection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Array of MmsMessage items */

public struct MmsMessageCollection: Codable {

    /** Media file you want to send */
    public var mediaFile: String
    /** Array of MmsMessage models */
    public var messages: [MmsMessage]

    public init(mediaFile: String, messages: [MmsMessage]) {
        self.mediaFile = mediaFile
        self.messages = messages
    }

    public enum CodingKeys: String, CodingKey { 
        case mediaFile = "media_file"
        case messages
    }


}

