//
// StrippedString.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** String to be stripped. */

public struct StrippedString: Codable {

    /** String to be. */
    public var stripString: String

    public init(stripString: String) {
        self.stripString = stripString
    }

    public enum CodingKeys: String, CodingKey { 
        case stripString = "strip_string"
    }


}

