//
// UploadFile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Your file to be uploaded. */

public struct UploadFile: Codable {

    /** Your base64 encoded file string. */
    public var content: String

    public init(content: String) {
        self.content = content
    }


}

