//
// VoiceMessageCollection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Array of VoiceMessage items */

public struct VoiceMessageCollection: Codable {

    /** Array of VoiceMessage items */
    public var messages: [VoiceMessage]

    public init(messages: [VoiceMessage]) {
        self.messages = messages
    }


}

