//
// AccountAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class AccountAPI {
    /**
     Get account information
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accountGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        accountGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get account information
     - GET /account
     - Get account details
     - BASIC:
       - type: basic
       - name: BasicAuth
     - examples: [{contentType=application/json, example=""}]

     - returns: RequestBuilder<String> 
     */
    open class func accountGetWithRequestBuilder() -> RequestBuilder<String> {
        let path = "/account"
        let URLString = ClickSendClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<String>.Type = ClickSendClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Create a new account
     
     - parameter account: (body) Account model 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accountPost(account: Account, completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        accountPostWithRequestBuilder(account: account).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Create a new account
     - POST /account
     - Create An Account
     - BASIC:
       - type: basic
       - name: BasicAuth
     - examples: [{contentType=application/json, example=""}]
     
     - parameter account: (body) Account model 

     - returns: RequestBuilder<String> 
     */
    open class func accountPostWithRequestBuilder(account: Account) -> RequestBuilder<String> {
        let path = "/account"
        let URLString = ClickSendClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: account)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<String>.Type = ClickSendClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Get account useage by subaccount
     
     - parameter year: (path) Year to filter by (yyyy) 
     - parameter month: (path) Month to filter by (mm) 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accountUseageBySubaccountGet(year: Int, month: Int, completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        accountUseageBySubaccountGetWithRequestBuilder(year: year, month: month).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get account useage by subaccount
     - GET /account/usage/{year}/{month}/subaccount
     - Get account useage by subaccount
     - BASIC:
       - type: basic
       - name: BasicAuth
     - examples: [{contentType=application/json, example=""}]
     
     - parameter year: (path) Year to filter by (yyyy) 
     - parameter month: (path) Month to filter by (mm) 

     - returns: RequestBuilder<String> 
     */
    open class func accountUseageBySubaccountGetWithRequestBuilder(year: Int, month: Int) -> RequestBuilder<String> {
        var path = "/account/usage/{year}/{month}/subaccount"
        let yearPreEscape = "\(year)"
        let yearPostEscape = yearPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{year}", with: yearPostEscape, options: .literal, range: nil)
        let monthPreEscape = "\(month)"
        let monthPostEscape = monthPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{month}", with: monthPostEscape, options: .literal, range: nil)
        let URLString = ClickSendClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<String>.Type = ClickSendClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Send account activation token
     
     - parameter accountVerify: (body) Account details 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accountVerifySendPut(accountVerify: AccountVerify, completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        accountVerifySendPutWithRequestBuilder(accountVerify: accountVerify).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Send account activation token
     - PUT /account-verify/send
     - Send account activation token
     - BASIC:
       - type: basic
       - name: BasicAuth
     - examples: [{contentType=application/json, example=""}]
     
     - parameter accountVerify: (body) Account details 

     - returns: RequestBuilder<String> 
     */
    open class func accountVerifySendPutWithRequestBuilder(accountVerify: AccountVerify) -> RequestBuilder<String> {
        let path = "/account-verify/send"
        let URLString = ClickSendClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: accountVerify)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<String>.Type = ClickSendClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Verify new account
     
     - parameter activationToken: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accountVerifyVerifyByActivationTokenPut(activationToken: Int, completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        accountVerifyVerifyByActivationTokenPutWithRequestBuilder(activationToken: activationToken).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Verify new account
     - PUT /account-verify/verify/{activation_token}
     - Verify new account
     - BASIC:
       - type: basic
       - name: BasicAuth
     - examples: [{contentType=application/json, example=""}]
     
     - parameter activationToken: (path)  

     - returns: RequestBuilder<String> 
     */
    open class func accountVerifyVerifyByActivationTokenPutWithRequestBuilder(activationToken: Int) -> RequestBuilder<String> {
        var path = "/account-verify/verify/{activation_token}"
        let activationTokenPreEscape = "\(activationToken)"
        let activationTokenPostEscape = activationTokenPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{activation_token}", with: activationTokenPostEscape, options: .literal, range: nil)
        let URLString = ClickSendClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<String>.Type = ClickSendClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Forgot password
     
     - parameter forgotPassword: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func forgotPasswordPut(forgotPassword: ForgotPassword? = nil, completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        forgotPasswordPutWithRequestBuilder(forgotPassword: forgotPassword).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Forgot password
     - PUT /forgot-password
     - Forgot password
     - BASIC:
       - type: basic
       - name: BasicAuth
     - examples: [{contentType=application/json, example=""}]
     
     - parameter forgotPassword: (body)  (optional)

     - returns: RequestBuilder<String> 
     */
    open class func forgotPasswordPutWithRequestBuilder(forgotPassword: ForgotPassword? = nil) -> RequestBuilder<String> {
        let path = "/forgot-password"
        let URLString = ClickSendClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: forgotPassword)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<String>.Type = ClickSendClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Verify forgot password
     
     - parameter verifyPassword: (body) verifyPassword data 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func forgotPasswordVerifyPut(verifyPassword: AccountForgotPasswordVerify, completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        forgotPasswordVerifyPutWithRequestBuilder(verifyPassword: verifyPassword).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Verify forgot password
     - PUT /forgot-password/verify
     - Verify forgot password
     - BASIC:
       - type: basic
       - name: BasicAuth
     - examples: [{contentType=application/json, example=""}]
     
     - parameter verifyPassword: (body) verifyPassword data 

     - returns: RequestBuilder<String> 
     */
    open class func forgotPasswordVerifyPutWithRequestBuilder(verifyPassword: AccountForgotPasswordVerify) -> RequestBuilder<String> {
        let path = "/forgot-password/verify"
        let URLString = ClickSendClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: verifyPassword)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<String>.Type = ClickSendClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Forgot username
     
     - parameter forgotUsername: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func forgotUsernamePut(forgotUsername: ForgotUsername? = nil, completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        forgotUsernamePutWithRequestBuilder(forgotUsername: forgotUsername).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Forgot username
     - PUT /forgot-username
     - Forgot username
     - examples: [{contentType=application/json, example=""}]
     
     - parameter forgotUsername: (body)  (optional)

     - returns: RequestBuilder<String> 
     */
    open class func forgotUsernamePutWithRequestBuilder(forgotUsername: ForgotUsername? = nil) -> RequestBuilder<String> {
        let path = "/forgot-username"
        let URLString = ClickSendClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: forgotUsername)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<String>.Type = ClickSendClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
