//
// CountriesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class CountriesAPI {
    /**
     Get all country codes
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func countriesGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        countriesGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get all country codes
     - GET /countries
     - Get all countries
     - examples: [{contentType=application/json, example=""}]

     - returns: RequestBuilder<String> 
     */
    open class func countriesGetWithRequestBuilder() -> RequestBuilder<String> {
        let path = "/countries"
        let URLString = ClickSendClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<String>.Type = ClickSendClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
