//
// DeliveryIssuesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class DeliveryIssuesAPI {
    /**
     Get all delivery issues
     
     - parameter page: (query) Page number (optional, default to 1)
     - parameter limit: (query) Number of records per page (optional, default to 10)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deliveryIssuesGet(page: Int? = nil, limit: Int? = nil, completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        deliveryIssuesGetWithRequestBuilder(page: page, limit: limit).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get all delivery issues
     - GET /delivery-issues
     - Get all delivery issues
     - BASIC:
       - type: basic
       - name: BasicAuth
     - examples: [{contentType=application/json, example=""}]
     
     - parameter page: (query) Page number (optional, default to 1)
     - parameter limit: (query) Number of records per page (optional, default to 10)

     - returns: RequestBuilder<String> 
     */
    open class func deliveryIssuesGetWithRequestBuilder(page: Int? = nil, limit: Int? = nil) -> RequestBuilder<String> {
        let path = "/delivery-issues"
        let URLString = ClickSendClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": page?.encodeToJSON(), 
            "limit": limit?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<String>.Type = ClickSendClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Create delivery Issue
     
     - parameter deliveryIssue: (body) DeliveryIssue model 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deliveryIssuesPost(deliveryIssue: DeliveryIssue, completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        deliveryIssuesPostWithRequestBuilder(deliveryIssue: deliveryIssue).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Create delivery Issue
     - POST /delivery-issues
     - Create delivery Issue
     - BASIC:
       - type: basic
       - name: BasicAuth
     - examples: [{contentType=application/json, example=""}]
     
     - parameter deliveryIssue: (body) DeliveryIssue model 

     - returns: RequestBuilder<String> 
     */
    open class func deliveryIssuesPostWithRequestBuilder(deliveryIssue: DeliveryIssue) -> RequestBuilder<String> {
        let path = "/delivery-issues"
        let URLString = ClickSendClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: deliveryIssue)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<String>.Type = ClickSendClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
