//
// InboundSMSRulesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class InboundSMSRulesAPI {
    /**
     Delete inbound sms automation
     
     - parameter inboundRuleId: (path) Inbound rule id 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func smsInboundAutomationDelete(inboundRuleId: Int, completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        smsInboundAutomationDeleteWithRequestBuilder(inboundRuleId: inboundRuleId).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Delete inbound sms automation
     - DELETE /automations/sms/inbound/{inbound_rule_id}
     - Delete inbound sms automation
     - BASIC:
       - type: basic
       - name: BasicAuth
     - examples: [{contentType=application/json, example=""}]
     
     - parameter inboundRuleId: (path) Inbound rule id 

     - returns: RequestBuilder<String> 
     */
    open class func smsInboundAutomationDeleteWithRequestBuilder(inboundRuleId: Int) -> RequestBuilder<String> {
        var path = "/automations/sms/inbound/{inbound_rule_id}"
        let inboundRuleIdPreEscape = "\(inboundRuleId)"
        let inboundRuleIdPostEscape = inboundRuleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{inbound_rule_id}", with: inboundRuleIdPostEscape, options: .literal, range: nil)
        let URLString = ClickSendClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<String>.Type = ClickSendClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get specific inbound sms automation
     
     - parameter inboundRuleId: (path) Inbound rule id 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func smsInboundAutomationGet(inboundRuleId: Int, completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        smsInboundAutomationGetWithRequestBuilder(inboundRuleId: inboundRuleId).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get specific inbound sms automation
     - GET /automations/sms/inbound/{inbound_rule_id}
     - Get specific inbound sms automation
     - BASIC:
       - type: basic
       - name: BasicAuth
     - examples: [{contentType=application/json, example=""}]
     
     - parameter inboundRuleId: (path) Inbound rule id 

     - returns: RequestBuilder<String> 
     */
    open class func smsInboundAutomationGetWithRequestBuilder(inboundRuleId: Int) -> RequestBuilder<String> {
        var path = "/automations/sms/inbound/{inbound_rule_id}"
        let inboundRuleIdPreEscape = "\(inboundRuleId)"
        let inboundRuleIdPostEscape = inboundRuleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{inbound_rule_id}", with: inboundRuleIdPostEscape, options: .literal, range: nil)
        let URLString = ClickSendClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<String>.Type = ClickSendClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Create new inbound sms automation
     
     - parameter inboundSmsRule: (body) Inbound sms rule model 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func smsInboundAutomationPost(inboundSmsRule: InboundSMSRule, completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        smsInboundAutomationPostWithRequestBuilder(inboundSmsRule: inboundSmsRule).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Create new inbound sms automation
     - POST /automations/sms/inbound
     - Create new inbound sms automation
     - BASIC:
       - type: basic
       - name: BasicAuth
     - examples: [{contentType=application/json, example=""}]
     
     - parameter inboundSmsRule: (body) Inbound sms rule model 

     - returns: RequestBuilder<String> 
     */
    open class func smsInboundAutomationPostWithRequestBuilder(inboundSmsRule: InboundSMSRule) -> RequestBuilder<String> {
        let path = "/automations/sms/inbound"
        let URLString = ClickSendClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: inboundSmsRule)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<String>.Type = ClickSendClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Update inbound sms automation
     
     - parameter inboundRuleId: (path) Inbound rule id 
     - parameter inboundSmsRule: (body) Inbound sms rule model 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func smsInboundAutomationPut(inboundRuleId: Int, inboundSmsRule: InboundSMSRule, completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        smsInboundAutomationPutWithRequestBuilder(inboundRuleId: inboundRuleId, inboundSmsRule: inboundSmsRule).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Update inbound sms automation
     - PUT /automations/sms/inbound/{inbound_rule_id}
     - Update inbound sms automation
     - BASIC:
       - type: basic
       - name: BasicAuth
     - examples: [{contentType=application/json, example=""}]
     
     - parameter inboundRuleId: (path) Inbound rule id 
     - parameter inboundSmsRule: (body) Inbound sms rule model 

     - returns: RequestBuilder<String> 
     */
    open class func smsInboundAutomationPutWithRequestBuilder(inboundRuleId: Int, inboundSmsRule: InboundSMSRule) -> RequestBuilder<String> {
        var path = "/automations/sms/inbound/{inbound_rule_id}"
        let inboundRuleIdPreEscape = "\(inboundRuleId)"
        let inboundRuleIdPostEscape = inboundRuleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{inbound_rule_id}", with: inboundRuleIdPostEscape, options: .literal, range: nil)
        let URLString = ClickSendClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: inboundSmsRule)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<String>.Type = ClickSendClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Get all inbound sms automations
     
     - parameter q: (query) Your keyword or query. (optional)
     - parameter page: (query) Page number (optional, default to 1)
     - parameter limit: (query) Number of records per page (optional, default to 10)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func smsInboundAutomationsGet(q: String? = nil, page: Int? = nil, limit: Int? = nil, completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        smsInboundAutomationsGetWithRequestBuilder(q: q, page: page, limit: limit).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get all inbound sms automations
     - GET /automations/sms/inbound
     - Get all inbound sms automations
     - BASIC:
       - type: basic
       - name: BasicAuth
     - examples: [{contentType=application/json, example=""}]
     
     - parameter q: (query) Your keyword or query. (optional)
     - parameter page: (query) Page number (optional, default to 1)
     - parameter limit: (query) Number of records per page (optional, default to 10)

     - returns: RequestBuilder<String> 
     */
    open class func smsInboundAutomationsGetWithRequestBuilder(q: String? = nil, page: Int? = nil, limit: Int? = nil) -> RequestBuilder<String> {
        let path = "/automations/sms/inbound"
        let URLString = ClickSendClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "q": q, 
            "page": page?.encodeToJSON(), 
            "limit": limit?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<String>.Type = ClickSendClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
