//
// SMSDeliveryReceiptRulesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class SMSDeliveryReceiptRulesAPI {
    /**
     Delete sms delivery receipt automation
     
     - parameter receiptRuleId: (path) Receipt rule id 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func smsDeliveryReceiptAutomationDelete(receiptRuleId: Int, completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        smsDeliveryReceiptAutomationDeleteWithRequestBuilder(receiptRuleId: receiptRuleId).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Delete sms delivery receipt automation
     - DELETE /automations/sms/receipts/{receipt_rule_id}
     - Delete sms delivery receipt automation
     - BASIC:
       - type: basic
       - name: BasicAuth
     - examples: [{contentType=application/json, example=""}]
     
     - parameter receiptRuleId: (path) Receipt rule id 

     - returns: RequestBuilder<String> 
     */
    open class func smsDeliveryReceiptAutomationDeleteWithRequestBuilder(receiptRuleId: Int) -> RequestBuilder<String> {
        var path = "/automations/sms/receipts/{receipt_rule_id}"
        let receiptRuleIdPreEscape = "\(receiptRuleId)"
        let receiptRuleIdPostEscape = receiptRuleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{receipt_rule_id}", with: receiptRuleIdPostEscape, options: .literal, range: nil)
        let URLString = ClickSendClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<String>.Type = ClickSendClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get specific sms delivery receipt automation
     
     - parameter receiptRuleId: (path) Receipt rule id 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func smsDeliveryReceiptAutomationGet(receiptRuleId: Int, completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        smsDeliveryReceiptAutomationGetWithRequestBuilder(receiptRuleId: receiptRuleId).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get specific sms delivery receipt automation
     - GET /automations/sms/receipts/{receipt_rule_id}
     - Get specific sms delivery receipt automation
     - BASIC:
       - type: basic
       - name: BasicAuth
     - examples: [{contentType=application/json, example=""}]
     
     - parameter receiptRuleId: (path) Receipt rule id 

     - returns: RequestBuilder<String> 
     */
    open class func smsDeliveryReceiptAutomationGetWithRequestBuilder(receiptRuleId: Int) -> RequestBuilder<String> {
        var path = "/automations/sms/receipts/{receipt_rule_id}"
        let receiptRuleIdPreEscape = "\(receiptRuleId)"
        let receiptRuleIdPostEscape = receiptRuleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{receipt_rule_id}", with: receiptRuleIdPostEscape, options: .literal, range: nil)
        let URLString = ClickSendClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<String>.Type = ClickSendClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Create sms delivery receipt automations
     
     - parameter deliveryReceiptRule: (body) sms delivery receipt rule model 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func smsDeliveryReceiptAutomationPost(deliveryReceiptRule: DeliveryReceiptRule, completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        smsDeliveryReceiptAutomationPostWithRequestBuilder(deliveryReceiptRule: deliveryReceiptRule).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Create sms delivery receipt automations
     - POST /automations/sms/receipts
     - Create sms delivery receipt automations
     - BASIC:
       - type: basic
       - name: BasicAuth
     - examples: [{contentType=application/json, example=""}]
     
     - parameter deliveryReceiptRule: (body) sms delivery receipt rule model 

     - returns: RequestBuilder<String> 
     */
    open class func smsDeliveryReceiptAutomationPostWithRequestBuilder(deliveryReceiptRule: DeliveryReceiptRule) -> RequestBuilder<String> {
        let path = "/automations/sms/receipts"
        let URLString = ClickSendClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: deliveryReceiptRule)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<String>.Type = ClickSendClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Update sms delivery receipt automation
     
     - parameter receiptRuleId: (path) Receipt rule id 
     - parameter deliveryReceiptRule: (body) Delivery receipt rule model 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func smsDeliveryReceiptAutomationPut(receiptRuleId: Int, deliveryReceiptRule: DeliveryReceiptRule, completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        smsDeliveryReceiptAutomationPutWithRequestBuilder(receiptRuleId: receiptRuleId, deliveryReceiptRule: deliveryReceiptRule).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Update sms delivery receipt automation
     - PUT /automations/sms/receipts/{receipt_rule_id}
     - Update sms delivery receipt automation
     - BASIC:
       - type: basic
       - name: BasicAuth
     - examples: [{contentType=application/json, example=""}]
     
     - parameter receiptRuleId: (path) Receipt rule id 
     - parameter deliveryReceiptRule: (body) Delivery receipt rule model 

     - returns: RequestBuilder<String> 
     */
    open class func smsDeliveryReceiptAutomationPutWithRequestBuilder(receiptRuleId: Int, deliveryReceiptRule: DeliveryReceiptRule) -> RequestBuilder<String> {
        var path = "/automations/sms/receipts/{receipt_rule_id}"
        let receiptRuleIdPreEscape = "\(receiptRuleId)"
        let receiptRuleIdPostEscape = receiptRuleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{receipt_rule_id}", with: receiptRuleIdPostEscape, options: .literal, range: nil)
        let URLString = ClickSendClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: deliveryReceiptRule)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<String>.Type = ClickSendClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Get all sms delivery receipt automations
     
     - parameter q: (query) Your keyword or query. (optional)
     - parameter page: (query) Page number (optional, default to 1)
     - parameter limit: (query) Number of records per page (optional, default to 10)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func smsDeliveryReceiptAutomationsGet(q: String? = nil, page: Int? = nil, limit: Int? = nil, completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        smsDeliveryReceiptAutomationsGetWithRequestBuilder(q: q, page: page, limit: limit).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get all sms delivery receipt automations
     - GET /automations/sms/receipts
     - Get all sms delivery receipt automations
     - BASIC:
       - type: basic
       - name: BasicAuth
     - examples: [{contentType=application/json, example=""}]
     
     - parameter q: (query) Your keyword or query. (optional)
     - parameter page: (query) Page number (optional, default to 1)
     - parameter limit: (query) Number of records per page (optional, default to 10)

     - returns: RequestBuilder<String> 
     */
    open class func smsDeliveryReceiptAutomationsGetWithRequestBuilder(q: String? = nil, page: Int? = nil, limit: Int? = nil) -> RequestBuilder<String> {
        let path = "/automations/sms/receipts"
        let URLString = ClickSendClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "q": q, 
            "page": page?.encodeToJSON(), 
            "limit": limit?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<String>.Type = ClickSendClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
