//
// TransferCreditAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class TransferCreditAPI {
    /**
     Transfer Credit
     
     - parameter resellerAccountTransferCredit: (body) ResellerAccountTransferCredit model 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func resellerTransferCreditPut(resellerAccountTransferCredit: ResellerAccountTransferCredit, completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        resellerTransferCreditPutWithRequestBuilder(resellerAccountTransferCredit: resellerAccountTransferCredit).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Transfer Credit
     - PUT /reseller/transfer-credit
     - Transfer Credit
     - BASIC:
       - type: basic
       - name: BasicAuth
     - examples: [{contentType=application/json, example=""}]
     
     - parameter resellerAccountTransferCredit: (body) ResellerAccountTransferCredit model 

     - returns: RequestBuilder<String> 
     */
    open class func resellerTransferCreditPutWithRequestBuilder(resellerAccountTransferCredit: ResellerAccountTransferCredit) -> RequestBuilder<String> {
        let path = "/reseller/transfer-credit"
        let URLString = ClickSendClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: resellerAccountTransferCredit)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<String>.Type = ClickSendClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
