//
// CountryListIds.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CountryListIds: Codable {

    /** Array of country ids */
    public var countryListIds: [CountryListId]

    public init(countryListIds: [CountryListId]) {
        self.countryListIds = countryListIds
    }

    public enum CodingKeys: String, CodingKey { 
        case countryListIds = "country_list_ids"
    }


}

