//
// CountryListId.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Id of the country */

public struct CountryListId: Codable {




}

