//
// EmailFrom.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** From Email object. */

public struct EmailFrom: Codable {

    /** Email address id of the recipient. */
    public var emailAddressId: String
    /** Name of the recipient. */
    public var name: String?

    public init(emailAddressId: String, name: String?) {
        self.emailAddressId = emailAddressId
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case emailAddressId = "email_address_id"
        case name
    }


}

