//
// ForgotUsername.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ForgotUsername: Codable {

    /** Email belonging to account. */
    public var email: String?
    /** Phone number belonging to account. */
    public var phoneNumber: String?

    public init(email: String?, phoneNumber: String?) {
        self.email = email
        self.phoneNumber = phoneNumber
    }

    public enum CodingKeys: String, CodingKey { 
        case email
        case phoneNumber = "phone_number"
    }


}

