//
// InboundSMSRule.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Model for Inbound SMS Rules */

public struct InboundSMSRule: Codable {

    /** Dedicated Number. Can be &#39;*&#39; to apply to all numbers. */
    public var dedicatedNumber: String
    /** Rule Name. */
    public var ruleName: String
    /** Message Search Type: 0&#x3D;Any message, 1&#x3D;starts with, 2&#x3D;contains, 3&#x3D;does not contain. */
    public var messageSearchType: Double
    /** Message search term. */
    public var messageSearchTerm: String
    /** Action to be taken (AUTO_REPLY, EMAIL_USER, EMAIL_FIXED, URL, SMS, POLL, GROUP_SMS, MOVE_CONTACT, CREATE_CONTACT, CREATE_CONTACT_PLUS_EMAIL, CREATE_CONTACT_PLUS_NAME_EMAIL CREATE_CONTACT_PLUS_NAME, SMPP, NONE). */
    public var action: String
    /** Action address. */
    public var actionAddress: String
    /** Enabled: Disabled&#x3D;0 or Enabled&#x3D;1. */
    public var enabled: Double
    /** post, get, or json. post by default */
    public var webhookType: String?

    public init(dedicatedNumber: String, ruleName: String, messageSearchType: Double, messageSearchTerm: String, action: String, actionAddress: String, enabled: Double, webhookType: String?) {
        self.dedicatedNumber = dedicatedNumber
        self.ruleName = ruleName
        self.messageSearchType = messageSearchType
        self.messageSearchTerm = messageSearchTerm
        self.action = action
        self.actionAddress = actionAddress
        self.enabled = enabled
        self.webhookType = webhookType
    }

    public enum CodingKeys: String, CodingKey { 
        case dedicatedNumber = "dedicated_number"
        case ruleName = "rule_name"
        case messageSearchType = "message_search_type"
        case messageSearchTerm = "message_search_term"
        case action
        case actionAddress = "action_address"
        case enabled
        case webhookType = "webhook_type"
    }


}

