//
// Url.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Your url. */

public struct Url: Codable {

    /** Your url. */
    public var url: String

    public init(url: String) {
        self.url = url
    }


}

