//
// Account.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Complete account details needed for the user. */

public struct Account: Codable {

    /** Your username */
    public var username: String
    /** Your password */
    public var password: String
    /** Your phone number in E.164 format. */
    public var userPhone: String
    /** Your email */
    public var userEmail: String
    /** Your first name */
    public var userFirstName: String
    /** Your last name */
    public var userLastName: String
    /** Your delivery to value. */
    public var accountName: String
    /** Your country */
    public var country: String

    public init(username: String, password: String, userPhone: String, userEmail: String, userFirstName: String, userLastName: String, accountName: String, country: String) {
        self.username = username
        self.password = password
        self.userPhone = userPhone
        self.userEmail = userEmail
        self.userFirstName = userFirstName
        self.userLastName = userLastName
        self.accountName = accountName
        self.country = country
    }

    public enum CodingKeys: String, CodingKey { 
        case username
        case password
        case userPhone = "user_phone"
        case userEmail = "user_email"
        case userFirstName = "user_first_name"
        case userLastName = "user_last_name"
        case accountName = "account_name"
        case country
    }


}

