//
// Address.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Base model for all address-related objects. */

public struct Address: Codable {

    /** Your address name. */
    public var addressName: String
    /** Your address line 1 */
    public var addressLine1: String
    /** Your city */
    public var addressCity: String
    /** Your postal code */
    public var addressPostalCode: String
    /** Your country */
    public var addressCountry: String
    /** Your address line 2 */
    public var addressLine2: String?
    /** Your state */
    public var addressState: String?

    public init(addressName: String, addressLine1: String, addressCity: String, addressPostalCode: String, addressCountry: String, addressLine2: String?, addressState: String?) {
        self.addressName = addressName
        self.addressLine1 = addressLine1
        self.addressCity = addressCity
        self.addressPostalCode = addressPostalCode
        self.addressCountry = addressCountry
        self.addressLine2 = addressLine2
        self.addressState = addressState
    }

    public enum CodingKeys: String, CodingKey { 
        case addressName = "address_name"
        case addressLine1 = "address_line_1"
        case addressCity = "address_city"
        case addressPostalCode = "address_postal_code"
        case addressCountry = "address_country"
        case addressLine2 = "address_line_2"
        case addressState = "address_state"
    }


}

