//
// Attachment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Email attachment */

public struct Attachment: Codable {

    /** The base64-encoded contents of the file. */
    public var content: String
    /** The type of file being attached. */
    public var type: String
    /** The name of the file being attached. */
    public var filename: String
    /** Inline for content that can be displayed within the email, or attachment for any other files. */
    public var disposition: String
    /** An ID for the content. */
    public var contentId: String

    public init(content: String, type: String, filename: String, disposition: String, contentId: String) {
        self.content = content
        self.type = type
        self.filename = filename
        self.disposition = disposition
        self.contentId = contentId
    }

    public enum CodingKeys: String, CodingKey { 
        case content
        case type
        case filename
        case disposition
        case contentId = "content_id"
    }


}

