//
// ContactListImport.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contact list import model */

public struct ContactListImport: Codable {

    /** URL of file to process */
    public var fileUrl: String
    /** Order of fields in file */
    public var fieldOrder: [String]

    public init(fileUrl: String, fieldOrder: [String]) {
        self.fileUrl = fileUrl
        self.fieldOrder = fieldOrder
    }

    public enum CodingKeys: String, CodingKey { 
        case fileUrl = "file_url"
        case fieldOrder = "field_order"
    }


}

