//
// DeliveryReceiptRule.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Model for a Delivery Receipt */

public struct DeliveryReceiptRule: Codable {

    /** Rule Name. */
    public var ruleName: String
    /** Match Type. 0&#x3D;All reports. */
    public var matchType: Double
    /** Action to be taken (AUTO_REPLY, EMAIL_USER, EMAIL_FIXED, URL, SMS, POLL, GROUP_SMS, MOVE_CONTACT, CREATE_CONTACT, CREATE_CONTACT_PLUS_EMAIL, CREATE_CONTACT_PLUS_NAME_EMAIL CREATE_CONTACT_PLUS_NAME, SMPP, NONE). */
    public var action: String
    /** Action address. */
    public var actionAddress: String
    /** Enabled: Disabled&#x3D;0 or Enabled&#x3D;1. */
    public var enabled: Double

    public init(ruleName: String, matchType: Double, action: String, actionAddress: String, enabled: Double) {
        self.ruleName = ruleName
        self.matchType = matchType
        self.action = action
        self.actionAddress = actionAddress
        self.enabled = enabled
    }

    public enum CodingKeys: String, CodingKey { 
        case ruleName = "rule_name"
        case matchType = "match_type"
        case action
        case actionAddress = "action_address"
        case enabled
    }


}

