//
// EmailTemplateNew.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Model for Email Templates */

public struct EmailTemplateNew: Codable {

    /** The intended name for the new template. */
    public var templateName: String
    /** The ID of the master template you want to base on. */
    public var templateIdMaster: Double

    public init(templateName: String, templateIdMaster: Double) {
        self.templateName = templateName
        self.templateIdMaster = templateIdMaster
    }

    public enum CodingKeys: String, CodingKey { 
        case templateName = "template_name"
        case templateIdMaster = "template_id_master"
    }


}

