//
// FaxMessage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Base model for Fax Messages */

public struct FaxMessage: Codable {

    /** Your method of sending e.g. &#39;wordpress&#39;, &#39;php&#39;, &#39;c#&#39;. */
    public var source: String?
    /** Recipient fax number in E.164 format. */
    public var to: String
    /** Your list ID if sending to a whole list. Can be used instead of &#39;to&#39;. */
    public var listId: Int?
    /** Your sender id. Must be a valid fax number. */
    public var from: String?
    /** Leave blank for immediate delivery. Your schedule time in unix format http://help.clicksend.com/what-is-a-unix-timestamp */
    public var schedule: Int?
    /** Your reference. Will be passed back with all replies and delivery reports. */
    public var customString: String?
    /** Recipient country. */
    public var country: String?
    /** An email address where the reply should be emailed to. */
    public var fromEmail: String?

    public init(source: String?, to: String, listId: Int?, from: String?, schedule: Int?, customString: String?, country: String?, fromEmail: String?) {
        self.source = source
        self.to = to
        self.listId = listId
        self.from = from
        self.schedule = schedule
        self.customString = customString
        self.country = country
        self.fromEmail = fromEmail
    }

    public enum CodingKeys: String, CodingKey { 
        case source
        case to
        case listId = "list_id"
        case from
        case schedule
        case customString = "custom_string"
        case country
        case fromEmail = "from_email"
    }


}

