//
// PostDirectMail.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Post direct mail model */

public struct PostDirectMail: Codable {

    /** Campaign name */
    public var name: String
    /** Campaign file URLs (maximum 2) */
    public var fileUrls: [String]
    /** Document size - A5 or DL */
    public var size: String
    /** PostDirectMailArea model */
    public var areas: [PostDirectMailArea]
    /** Leave blank for immediate delivery. Your schedule time in unix format. */
    public var schedule: Int?
    /** Your method of sending e.g. &#39;wordpress&#39;, &#39;php&#39;, &#39;c#&#39;. */
    public var source: String?
    /** A custom string for your own reference */
    public var customString: String?

    public init(name: String, fileUrls: [String], size: String, areas: [PostDirectMailArea], schedule: Int?, source: String?, customString: String?) {
        self.name = name
        self.fileUrls = fileUrls
        self.size = size
        self.areas = areas
        self.schedule = schedule
        self.source = source
        self.customString = customString
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case fileUrls = "file_urls"
        case size
        case areas
        case schedule
        case source
        case customString = "custom_string"
    }


}

