//
// PostDirectMailArea.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** PostDirectMailArea model */

public struct PostDirectMailArea: Codable {

    /** Location ID to send to */
    public var locationId: Int
    /** Number of items to send */
    public var quantity: Int

    public init(locationId: Int, quantity: Int) {
        self.locationId = locationId
        self.quantity = quantity
    }

    public enum CodingKeys: String, CodingKey { 
        case locationId = "location_id"
        case quantity
    }


}

