//
// SmsMessageCollection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Array of SmsMessage items */

public struct SmsMessageCollection: Codable {

    /** Array of SmsMessage items */
    public var messages: [SmsMessage]

    public init(messages: [SmsMessage]) {
        self.messages = messages
    }


}

