//
// SmsTemplate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** SmsTemplate model */

public struct SmsTemplate: Codable {

    /** Name of template */
    public var templateName: String
    /** Body of template */
    public var body: String

    public init(templateName: String, body: String) {
        self.templateName = templateName
        self.body = body
    }

    public enum CodingKeys: String, CodingKey { 
        case templateName = "template_name"
        case body
    }


}

