//
// Subaccount.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Accounts that are maintained under a main account */

public struct Subaccount: Codable {

    /** Your new api username. */
    public var apiUsername: String
    /** Your new password */
    public var password: String
    /** Your new email. */
    public var email: String
    /** Your phone number in E.164 format. */
    public var phoneNumber: String
    /** Your firstname */
    public var firstName: String
    /** Your lastname */
    public var lastName: String
    /** Your access users flag value, must be 1 or 0. */
    public var accessUsers: Int?
    /** Your access billing flag value, must be 1 or 0. */
    public var accessBilling: Int?
    /** Your access reporting flag value, must be 1 or 0. */
    public var accessReporting: Int?
    /** Your access contacts flag value, must be 1 or 0. */
    public var accessContacts: Int?
    /** Your access settings flag value, must be 1 or 0. */
    public var accessSettings: Int?

    public init(apiUsername: String, password: String, email: String, phoneNumber: String, firstName: String, lastName: String, accessUsers: Int?, accessBilling: Int?, accessReporting: Int?, accessContacts: Int?, accessSettings: Int?) {
        self.apiUsername = apiUsername
        self.password = password
        self.email = email
        self.phoneNumber = phoneNumber
        self.firstName = firstName
        self.lastName = lastName
        self.accessUsers = accessUsers
        self.accessBilling = accessBilling
        self.accessReporting = accessReporting
        self.accessContacts = accessContacts
        self.accessSettings = accessSettings
    }

    public enum CodingKeys: String, CodingKey { 
        case apiUsername = "api_username"
        case password
        case email
        case phoneNumber = "phone_number"
        case firstName = "first_name"
        case lastName = "last_name"
        case accessUsers = "access_users"
        case accessBilling = "access_billing"
        case accessReporting = "access_reporting"
        case accessContacts = "access_contacts"
        case accessSettings = "access_settings"
    }


}

