//
// EmailTemplateUpdate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Model for Email Templates */

public struct EmailTemplateUpdate: Codable {

    /** The intended name for the template. */
    public var templateName: String?
    /** Your template body. */
    public var body: String

    public init(templateName: String?, body: String) {
        self.templateName = templateName
        self.body = body
    }

    public enum CodingKeys: String, CodingKey { 
        case templateName = "template_name"
        case body
    }


}

