//
// EmailRecipient.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Recipient of an email, either To, Cc, or Bcc. */

public struct EmailRecipient: Codable {

    /** Email of the recipient. */
    public var email: String
    /** Name of the recipient. */
    public var name: String?

    public init(email: String, name: String?) {
        self.email = email
        self.name = name
    }


}

