//
// CreditCard.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Credit card model */

public struct CreditCard: Codable {

    /** Credit card number */
    public var number: String
    /** Expiry month of credit card */
    public var expiryMonth: Int
    /** Expiry year of credit card */
    public var expiryYear: Int
    /** CVC number of credit card */
    public var cvc: Int
    /** Name printed on credit card */
    public var name: String
    /** Name of bank that credit card belongs to */
    public var bankName: String

    public init(number: String, expiryMonth: Int, expiryYear: Int, cvc: Int, name: String, bankName: String) {
        self.number = number
        self.expiryMonth = expiryMonth
        self.expiryYear = expiryYear
        self.cvc = cvc
        self.name = name
        self.bankName = bankName
    }

    public enum CodingKeys: String, CodingKey { 
        case number
        case expiryMonth = "expiry_month"
        case expiryYear = "expiry_year"
        case cvc
        case name
        case bankName = "bank_name"
    }


}

